package com.github.rd.jlv.pfers;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Properties;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class PreferenceStore {
    
    private final Logger logger = LoggerFactory.getLogger(getClass());

    private Properties props;
    
    private Properties defaultProps;

    private Path propsFilePath;
    
    public PreferenceStore() {
        props = new Properties();
        defaultProps = new Properties();
        propsFilePath = Paths.get("src", "main", "resources", "jlv.gui.properties");
    }
    
    public void load() {
        try(InputStream input = Files.newInputStream(propsFilePath)) {
            props.load(input);
        } catch (IOException e) {
            logger.error(e.getMessage(), e);
        }
    }
    
    public void loadDefault() {

    }

    public void store() {
        try(OutputStream output = Files.newOutputStream(propsFilePath)) {
            props.store(output, "Gui properties file generated by JLV");
        } catch (IOException e) {
            logger.error(e.getMessage(), e);
        }
    }
}
